name: Docker Image CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build Jar
      run: ./gradlew clean test

  deploy-development:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - name: deploy-development
        run: echo 'Deploying Development'

  deploy-pre-production:
    needs: deploy-development
    runs-on: ubuntu-latest
    environment: pre-production
    if: success() && github.ref == 'refs/heads/master'

    steps:
    - name: deploy-pre-production
      run: echo 'Deploying Pre-Production'

  deploy-production:
    needs: deploy-pre-production
    runs-on: ubuntu-latest
    environment: production
    if: success() && github.ref == 'refs/heads/master'

    steps:
    - name: deploy-production
      run: echo 'Deploying Production'
